project_id = "rymywtllzgysesdzstof"

[auth]
enable_signup = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.url]
site_url = "https://my-rescue-rewards.lovable.app"
additional_redirect_urls = ["https://my-rescue-rewards.lovable.app/auth?confirmed=true", "https://my-rescue-rewards.lovable.app/reset-password"]

[functions.reset-password]
verify_jwt = false

[functions.resend-confirmation]
verify_jwt = false
